---
title: "Recycled Paper Notebook Set"
subtitle: "Handcrafted journals with Lokta fabric cover and upcycled newspaper pencil"
categories: [Recycled Paper, Stationery, Journals]
filters:
  - carousel
css: ../../../assets/css/styles-product-pages.css
---

::: {.grid}

::: {.g-col-8}
<!-- Insert Product Images below -->
:::: {.carousel .dark controls="true" indicators="true"  autoplay="true" duration=2000}

:::: {.carousel-item image="../../../assets/media/images/products/blue-brick-with-flower.jpg" caption="Blue Brick with Flower"}
:::
:::: {.carousel-item image="../../../assets/media/images/products/purple-foliage.jpg" caption="Purple Foliage"}
:::
:::: {.carousel-item image="../../../assets/media/images/products/pink-hexagon-flower.jpg" caption="Pink Hexagon Flower"}
:::
:::: {.carousel-item image="../../../assets/media/images/products/red-foliage.jpg" caption="Red Foliage"}
:::
:::: {.carousel-item image="../../../assets/media/images/products/blue-and-golden-herringbone.jpg" caption="Blue and Golden Herringbone"}
:::

:::
<!-- end carousel -->
:::
<!-- end g-col-8 -->

::: {.g-col-4}
<!-- Product Details Section -->
<div class="product-details">
  <p>
    <span class="label" id="price-label">Price:</span>
    <span class="value" id="price-value">रू 760.00</span>
  </p>
  <p>
    <span class="label" id="availability-label">Availability:</span>
    <span class="value" id="availability-value">In stock</span>
  </p>
  <p>
    <span class="label" id="sku-label">SKU:</span>
    <span class="value" id="sku-value">RPNA5</span>
  </p>
</div>

#### Specifications
- 40 blank pages of 100% recycled paper
- Approximately 8.3" x 5.9" and 6" x 4.3"
- Ribbon page marker
- Hardbound with patterned Lokta cover
- Pen loop with upcycled newspaper pencil
:::
<!-- end g-col-4 -->
::: 
<!-- end grid -->

#### Description
Hand crafted in Nepal, this set of multi-functional journals is made with 100% post-consumer recycled paper and is perfect for your note-taking/ journaling needs. 

- 40 blank pages of 100% recycled paper
- Approximately 8.3" x 5.9"
- Ribbon page marker
- Hardbound with patterned Lokta cover
- Pen loop with upcycled newspaper pencil

The size of the journal makes it a perfect diary, notebook or a gift for your loved ones. Recycled paper is suitable for pencil and ballpoint pen.

Our products are handmade; slight variation in color, size, shape and texture make our each piece unique and special.

All our paper products are tree-free!